### ISSUE TITLE
mathtools support broken for v3?

### ISSUE THREAD

**Issue by peppobon** [transpect/idml2xml#3]
When exporting to idml with  mathtools v3 and the mathml string goes in a MathToolsML *attribute*, not in an element as implied by the <p:viewport match="MathToolsML"> in idml2hub.xpl.

To get the hub.xml I have to move the MathToolsML attribute as an element under CharacterStyleRange/Properties, but then there are paragraph splitting issues in SeparateParagraphs.xsl. 

Attached is a simple idml test case exported from mathtools
[test.idml.zip](https://github.com/transpect/idml2xml/files/2596403/test.idml.zip)
 v3.

**Comment by gimsieke** [comment]
It is an unfortunate choice of MathTools to store escaped XML in attributes. I need to try to use XSLT 3 in order to make it work with an open-source Saxon that supports XSLT 3. This requires that you use XML Calabash with Saxon 9.8, either from https://github.com/transpect/calabash-frontend/tree/saxon98 (with submodules) or from https://subversion.le-tex.de/common/github-mirror/calabash_saxon_9.8/

**Comment by peppobon** [comment]
what about adding an extra step in idml2xml.xpl before
remove-xml-declaration, to add an element under Properties?

<p:choose>
    <p:when test="$build-MathML-from-MathTools = 'yes'">
      <p:xslt name="add-mathtools-element">
          <p:input port="stylesheet">
            <p:inline>
              <xsl:stylesheet version="2.0">
                <xsl:template match="@*|node()">
                  <xsl:copy>
                    <xsl:apply-templates select="@*|node()"/>
                  </xsl:copy>
                </xsl:template>
                <xsl:template match="*:CharacterStyleRange/@MathToolsML"/>
                <xsl:template match=
"*:CharacterStyleRange[@MathToolsML]/Properties">
                  <Properties>
                    <xsl:apply-templates select="@*|node()"/>
                    <MathToolsML>
                      <xsl:value-of select="../@MathToolsML"/>
                    </MathToolsML>
                  </Properties>
                </xsl:template>
              </xsl:stylesheet>
            </p:inline>
          </p:input>
          <p:input port="parameters"><p:empty/></p:input>
        </p:xslt>
    </p:when>
    <p:otherwise>
      <p:identity/>
    </p:otherwise>
  </p:choose>


In this way we can still use xslt2.

**Comment by gimsieke** [comment]
No, `<xsl:value-of select="../@MathToolsML"/>` will only insert a text node with escaped XML source code. We need to apply the XPath 3.1 function [`fn:parse-xml()`](https://www.w3.org/TR/xpath-functions-31/#func-parse-xml) to the attribute value.

**Comment by gimsieke** [comment]
After I made it work with XSLT 3, I saw that the MathTools markup was escaped XML before, too. 
XProc’s `p:unescape-markup` turned it into XML proper. So instead of using XSLT 3, I moved the attribute to `Properties/MathToolsML`, almost as you proposed (creating a `Properties` element if need be, in addition to your proposal). This happens in the first XSLT pass, therefore I didn’t have to introduce a new pass.

**Comment by peppobon** [comment]
Thanks Gerrit, we are almost there. 

The conversion now works, but there is probably an edge case.

When converting the test.idml.zip attached above, you will se that there is something going wrong in SeparateParagraphs.xsl, as formulas on consecutive runs on a same line gets duplicated. Note that each formula has been typesetted using more than one mathtool box (separated by = entered as normal text), so there are different math/text runs.

See the attached files:
input indd:
![math-test_input-idml](https://user-images.githubusercontent.com/1643256/48763689-170d1c80-ecae-11e8-9c0e-feb287468dc1.png)
html output:
![math-test_out-html](https://user-images.githubusercontent.com/1643256/48763690-170d1c80-ecae-11e8-9b41-3c7999345ee3.png)
debug-out1: idml2xml.22.idml2xml_SeparateParagraphs-pull-down-psrange.xml (this is ok)
debug-out2: idml2xml.24.idml2xml_SeparateParagraphs.xml (here duplicate formulas gets inserted for the first time)
[idml2xml-debug-out.zip](https://github.com/transpect/idml2xml/files/2598984/idml2xml-debug-out.zip)

I think there is something going wrong in idml2xml:split-at-br in SeparateParagraphs.xsl

**Comment by gimsieke** [comment]
I changed something – already before noon, but I was too busy to look at the results until now. I think it’s looking good now.

**Comment by peppobon** [comment]
Sorry Gerrit, but transforming the test.idml I still get dups (and yes, I
did a .git pull).

**Comment by gimsieke** [comment]
Yes, you’re right. It was another change (commenting out https://github.com/transpect/idml2xml/blob/master/xsl/modes/SeparateParagraphs.xsl#L122) that led to the correct result. Need to investigate further.

**Comment by gimsieke** [comment]
Please try it again.

**Comment by peppobon** [comment]
Yes! Now it works perfectly.
Thank you for having fixed this.
__peppo
