### ISSUE TITLE
dropped content

### ISSUE THREAD

**Issue by peppobon** [transpect/idml2xml#5]
Hi Gerrit,
attached are two idml test cases and the two corresponding hub.xml (conversion made with the latest git pull).
In the file test_no_mml.hub.xml everything is ok.
In the file test_with_mml.hub.xml the content of the para before the table is missing.

It seems that the issue arise only when you have mml and a Content and a Table in the same CharacterStyleRange, but not always, as I have files where only some paras gets dropped.

I have solved the problem by editing the source indd and making sure all tables are in their CharacterStyleRange with no other Content elements, but I think this should be investigated further.
[test-case.zip](https://github.com/transpect/idml2xml/files/6630171/test-case.zip)

**Comment by gimsieke** [comment]
Hi Peppo,
Thanks for reporting it. We are all very busy right now, so I can’t promise when we will be able to analyze and fix it, and who is going to do it. I hope that some colleague can squeeze it in.
Gerrit

**Comment by mkraetke** [comment]
Hi Peppo,

I made a fix to MathTools processing and hope this will solve your issue.

Best, Martin

**Comment by peppobon** [comment]
Yes, Problem solved!
Thanks Martin
