### ISSUE TITLE
dropped content in idml2xml:XML-Hubformat-extract-frames mode

### ISSUE THREAD

**Issue by peppobon** [transpect/idml2xml#6]
Hello,
when converting the attached idml the sidebar content get lost and only anchors are present:
    <sidebar remap="Group" role="sp-figure-container">
        <anchor xml:id="id_d5267e54"/>
        <anchor xml:id="id_d5267e87"/>
    </sidebar>

The content is ok in output from previous step in idml2xml.HUB.07a.idml2xml_XML-Hubformat-properties2atts.xml

I think the problem is in mode idml2xml:XML-Hubformat-extract-frames templates in GenerateHubformat.xsl 

Tested with latest 2beb2b8..b6ce1ad
Attaches the idml test doc and the generated hub.

Thanks
[test.zip](https://github.com/transpect/idml2xml/files/7576156/test.zip)

**Comment by peppobon** [comment]
Forgot to mention that if you anchor the group to a para the conversion is ok.

**Comment by gimsieke** [comment]
If I restore the behavior before [this fix](https://github.com/transpect/idml2xml/blame/master/xsl/modes/GenerateHubformat.xsl#L1392), I think the lost content will be retained. Now checking how to reconcile this behavior with the duplicate-content issue that the previous fix was meant to address.

**Comment by gimsieke** [comment]
I hope that I was able to fix it while still avoiding the other issue that made me change the template in the first place. Please have a try.

**Comment by peppobon** [comment]
Sorry, but now I get the content twice.
See the same file converted after your patch.
[test-after-patch.idml.hub.zip](https://github.com/transpect/idml2xml/files/7576685/test-after-patch.idml.hub.zip)
.

**Comment by peppobon** [comment]
the two inner sidebars hub/sidebar[1]/sidebar are repeated after hub/sidebar[1].
The right content should be  hub/sidebar[1] only

**Comment by gimsieke** [comment]
hmm. Investigating…

**Comment by gimsieke** [comment]
I didn’t mean to mark it as resolved. It was just an _attempt_ at resolving the issue. All tests of the other projects that use this library need to pass.

**Comment by gimsieke** [comment]
But you may already test whether this would work in your case, @peppobon.

**Comment by peppobon** [comment]
Yes! my tests now pass.
Thanks Gerrit (as always).

**Comment by gimsieke** [comment]
To be honest, I didn’t exactly know what I was doing. We need to monitor this. It may also be that we will detect side effects with other projects. Due to intermittent issues with Github’s svn bridge, we cannot test some of our projects yet.
