### ISSUE TITLE
edge case with mathtools v3

### ISSUE THREAD

**Issue by peppobon** [transpect/idml2xml#7]
Hi,
I have encountered an edge case when converting from mathtools to mml (see attached idml).

Mathtool sometimes (I do not understand when|why) emit an empty `@MathToolsML` on a charrange containing text content and this content get lost due to the `<p:delete name="remove-MathTools-Markup"...` line in idml2hub.xpl.

Solution is to modyfy above line from
`<p:delete name="remove-MathTools-Markup" 
        match="*[@MTMathZone][not(descendant::mml:math or descendant::Rectangle)]
                      |CharacterStyleRange[descendant::mml:math]/Content[not(normalize-space())]"/>`
to
`<p:delete name="remove-MathTools-Markup" 
        match="*[@MTMathZone][not(descendant::mml:math or descendant::Rectangle)][not(MathToolsML='')]
                      |CharacterStyleRange[descendant::mml:math]/Content[not(normalize-space())]"/>`

I think this should be pretty safe and (hopefully) should not introduce any regression.

[test.idml.zip](https://github.com/transpect/idml2xml/files/7996289/test.idml.zip)

**Comment by gimsieke** [comment]
I haven’t looked at the code and at the input yet, but if you say that sometimes `@MathToolsMl` is empty, shouldn’t it read `[not(@MathToolsML='')]` instead of `[not(MathToolsML='')]`?

**Comment by peppobon** [comment]
> I haven’t looked at the code and at the input yet, but if you say that sometimes `@MathToolsMl` is empty, shouldn’t it read `[not(@MathToolsML='')]` instead of `[not(MathToolsML='')]`?

No, because `@MathToolsMl` has been  already transformed to `<MathToolsML>` in a previous step.
I have tested the above code and it works.

**Comment by gimsieke** [comment]
I applied the change directly here on Github. Let’s see what our integration tests say…

**Comment by gimsieke** [comment]
The tests haven’t complained. I don’t think we have very broad coverage of MathTools content anyway. If it’s working for you, you might close this issue.

**Comment by peppobon** [comment]
Yes, it is ok for me.
